services:
  minio:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    entrypoint: |
      /bin/sh -c "
        /usr/bin/docker-entrypoint.sh minio server /data --console-address \":9001\" &
        sleep 10
        mc alias set myminio http://localhost:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
        mc mb --ignore-existing myminio/minioadmin &&
        mc anonymous set download myminio/minioadmin &&
        wait
      "
volumes:
  minio_data:
